version: "3.8"
services:
  app:
    container_name: backend_app
    build:
      context: ${ROOT_DIR}/backend/.
      dockerfile: ${ROOT_DIR}/backend/app.dockerFile
    ports:
      - "3002:3000"
    networks:
      - fullstack
    volumes:
      - ${ROOT_DIR}/backend:/usr/src/app
    env_file:
      - ${ROOT_DIR}/backend/.env
networks:
  fullstack:
    external: true
