version: "3.8"
services:
   mysql-db:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=my-ticket
      - MYSQL_USER=my-ticket
      - MYSQL_PASSWORD=supperadmin
      - MYSQL_ROOT_PASSWORD=supperadmin
    ports:
      - 3456:3306
    networks:
      - fullstack

networks:
  fullstack:
    name: fullstack
    driver: bridge
